### ISSUE TITLE
Add default values for all the services questions

### ISSUE THREAD

**Issue by xredo** [MarsBased/pathfinder-rails#9]
There are some questions with default values and some of them without. We must always offer a default value based in our experience building projects.

**Comment by xredo** [comment]
We need to discuss what are the default values for every possible option. @fjsanpedro Can you add the list of options that are currently available?

**Comment by fjsanpedro** [comment]
The options are:
- Carrierwave (default: no)
  - minimagick (default: no)
- Rollbar, Airbrake, none (default: none)
- Datepicker (deafult: no)
- Paranoia (deafult: no)
- Ransack (default: no)
- Searchkick (default: no)

**Comment by xredo** [comment]
I would also add:

- Simple form (default: marsman)

**Comment by xredo** [comment]
- DB adapter (default: Postgresql)

**Comment by pablorc** [comment]
There are new questions:

- active_admin (default: yes)

Let's add questions for:

- Want to use tests? (default: yes)

We're not going to make any change on DB adapter, since it is going to change in an upcoming issue (https://github.com/MarsBased/pathfinder-rails/issues/50).

The questions and default answers provided before looks fine to us.

**Comment by xredo** [comment]
We need to discuss if this issue makes sense now that we have Rails current implementation in Rails 5.1+ https://api.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html
